# Generated by Django 2.2.2 on 2019-06-26 07:33

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Others')], max_length=10)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('mode', models.CharField(choices=[('Entrance Exam', 'Entrance Exam'), ('File Study', 'File Study')], max_length=20, verbose_name='Select Mode')),
                ('level', models.CharField(choices=[('BTS1', 'BTS 1'), ('BTS2', 'BTS 2'), ('LICENCE', 'Licence Pro')], max_length=20, verbose_name='Select Level')),
                ('cni', models.FileField(upload_to='documents/', verbose_name='National ID Card')),
                ('birth_certificate', models.FileField(upload_to='documents/', verbose_name='Birth Certificate')),
                ('gce', models.FileField(upload_to='documents/', verbose_name='GCE A-Levels')),
                ('bts1', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='BTS 1')),
                ('bts2', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='BTS 2')),
                ('bachelor', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Bachelor')),
                ('entry_date', models.DateField()),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='added on')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='updated on')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='added on')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='updated on')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Give the session a name', max_length=50, verbose_name='Session Name')),
                ('month', models.CharField(max_length=50)),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='added on')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='updated on')),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='added on')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='updated on')),
            ],
            options={
                'verbose_name_plural': 'Specialities',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Others')], max_length=10)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='added on')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='updated on')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
