# Generated by Django 2.2.2 on 2019-06-26 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apply', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apply.Field'),
        ),
        migrations.AddField(
            model_name='document',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apply.Session'),
        ),
        migrations.AddField(
            model_name='document',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apply.Speciality'),
        ),
        migrations.AddField(
            model_name='document',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
