# Generated by Django 2.2.2 on 2019-06-26 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0002_auto_20190626_0733'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
