# Generated by Django 2.2.2 on 2019-06-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(help_text='Enter your area of residence', max_length=100, verbose_name='Address'),
        ),
    ]
